Repository mvisonneau/gitlab-ci-pipelines-exporter, pull requests merged in 2020-04, with the labels that each got.

#80 Add vars for project and ref on example Grafana dashboard
  example/grafana/dashboard.json
Labels: enhancement

#85 Add pipeline status “manual”
  cmd/gitlab.go
Labels: enhancement

#89 Fix lingering status metrics from previous jobs
  cmd/gitlab.go
Labels: bug

#88 concurrent projects polling; syntax fixes
  CHANGELOG.md
  README.md
  chart/values.yaml
  cmd/config.go
  cmd/config_test.go
  cmd/exporter.go
  cmd/exporter_test.go
  cmd/gitlab.go
  cmd/gitlab_test.go
Labels: enhancement

#93 Adding pipeline variables metrics & refactored general logic implementation
  .gitignore
  CHANGELOG.md
  README.md
  cmd/config.go
  cmd/config_test.go
  cmd/exporter.go
  cmd/exporter_test.go
  cmd/gitlab.go
  cmd/gitlab_test.go
  cmd/metrics.go
  cmd/metrics_test.go
Labels: bug, enhancement
